### ISSUE TITLE
deployment scripts blow away history of the target branch

### ISSUE THREAD

**Issue by Fryguy** [RedHatInsights/insights-frontend-builder-common#10]
The reason this happens is because it does a `git init` in the directory, then an initial commit, then a force push into the target branch.  Since the commit was not built on previous history, everything in history is lost.

cc @iphands

**Comment by iphands** [comment]
Yeah when I first saw this it was jarring for me too.

We are just using Git as a staging area here to have some light ACLs in place before pushing things forward (though they can be worked around atm). We were going to rsync the data straight to the destination w/o landing it on Git initially.

I guess given that... why do you want there to be history? What is it stopping you from doing?

**Comment by Fryguy** [comment]
The history is useful to see any changes in time with what's deployed.  If we have to rollback to a particular build, or see what changed between a good and bad build, this repo is the only place that those "compiled" dist directories are stored.  Rebuilding from a particular SHA on the source repo is doable, but given dependency changes (both in packages and in the building tools like npm, webpack, etc), you can never truly get back to where you were.
